name: Build
on:
  push:
    branches:
      - '**'  
  pull_request:
    branches:
      - master
      - master-3.0

jobs:
  build:
    runs-on: windows-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup node 12
        uses: actions/setup-node@v2
        with:
          node-version: 12.x
      - uses: c-hive/gha-yarn-cache@v1
      - name: Install JS dependencies
        run: yarn install
      - name: Test
        run: yarn test
